import type { GetStaticProps, NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import styles from '../styles/Home.module.css'
import { GetChartacterResults } from '../types'
import { Character } from './../types';

const Home: NextPage<{characters:Character[]}> = ({ characters }) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>  
        <Link href={'/hooks'}>
          <a>
            <h3>hooks</h3>
          </a>
        </Link>
        <p>---------------------------------------------------</p>
        {characters.map((character)=>{
          return <div key={character.id}>
              <Link href={`/characters/${character.id}`}>
                <a>
                  <h3>{character.name}</h3>
                </a>
              </Link>
            <Image src={character.image} alt={character.name} width={200} height={200}/>
            </div>
        })}
      </main>
    </div>
  )
}
export const getStaticProps: GetStaticProps = async (context) => {
  const res = await fetch("https://rickandmortyapi.com/api/character");
  const { results }:GetChartacterResults = await res.json();

  return {
    props: {
      characters: results
    }
  }
}
export default Home
